### ISSUE TITLE
Unable to select regions

### ISSUE THREAD

**Issue by markdane** [labsyspharm/Visinity#11]
While using the sample data set, I am unable to select regions on the image in the center of the screen. I can zoom and pan this image. I'm using an M1 Mac running Monterrey 12.5.1. The Channels, Pairwise correlation and Neighborhood composition panels seem to be working.

**Comment by simonwarchol** [comment]
Hey @markdane,
Looking into this now. Are you using the `Ton_378_Cropped.ome.tif` or `Ton_378_Cropped_Small.ome.tif` dataset?

**Comment by markdane** [comment]
I used the Ton_378_Cropped_Small.ome.tif dataset.

**Comment by simonwarchol** [comment]
Hmm i'm not able to reproduce. You're using shift+click to select regions? I'm going to push up a small change right now and if things still don't work i could meet quickly today / tomorrow to debug :)
-Simon

**Comment by markdane** [comment]
It’s working for me now on the sample data. Thanks!

From: Simon Warchol ***@***.***>
Reply-To: labsyspharm/Visinity ***@***.***>
Date: Wednesday, October 5, 2022 at 6:24 AM
To: labsyspharm/Visinity ***@***.***>
Cc: Mark Dane ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [labsyspharm/Visinity] Unable to select regions (Issue #11)


Hmm i'm not able to reproduce. You're using shift+click to select regions? I'm going to push up a small change right now and if things still don't work i could meet quickly today / tomorrow to debug :)
-Simon
